name: Build Kernel
on:
  push:
    branches:    
      - miui
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: false
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Init Repo
      run: |
        cd ~
        git clone https://github.com/Blankeer/android_kernel_xiaomi_sm8250 -b miui --depth=1 
    - name: Build With Shell
      run: |
        cd ~/android_kernel_xiaomi_sm8250
        bash build_full.sh
    - name: Package With AnyKernel
      run: |
        cd ~/AnyKernel/
        cp ../android_kernel_xiaomi_sm8250/out/arch/arm64/boot/Image.gz-dtb  ./
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: umi_kernel_blanke
        path: /home/runner/AnyKernel/
